### ISSUE TITLE
set_output_summary: Use summary when no description

### ISSUE THREAD

**Issue by janezd** [biolab/orange-widget-base#109]
@PrimozGodec wrote in https://github.com/biolab/orange3/pull/4904

> Note: self.info.set_output_summary(summary, summary) is used since in the cases with string summary and empty description, the description is not set automatically to same value than it is done for int summary. I suggest merging this PR as it is and unifying those behaviours in the widget base. I would be happy to submit the PR.

**Comment by irgolic** [comment]
Could summaries not be automated altogether by traversing the list of input/output signals and updating each time the signal receives/sends new data?
