### ISSUE TITLE
PDF export broken, no points shown

### ISSUE THREAD

**Issue by irgolic** [biolab/orange-widget-base#111]
##### Orange version
master

##### Expected behavior
PDF export shows what is shown in widget.

##### Actual behavior
PDF export shows everything except points/selection/labels.

##### Steps to reproduce the behavior
File (Iris) -> Scatterplot

Press save, choose PDF from dropdown, save it, open it.

##### Additional info (worksheets, data, screenshots, ...)

Env:
- macOS 10.15
- PyQt5==5.15.1
- pyqtgraph==0.11.0

![Screenshot 2020-10-27 at 20 56 07](https://user-images.githubusercontent.com/24586651/97355183-d6a17a80-1896-11eb-8ad3-f07af7020a3b.png)
![Screenshot 2020-10-27 at 20 56 12](https://user-images.githubusercontent.com/24586651/97355196-d99c6b00-1896-11eb-97da-e16e01a16fa3.png)

**Comment by markotoplak** [comment]
Confirmed on my computer, with PyQt 5.14 and pyqtgraph 0.11.0.

When I downgraded pyqtgraph to 0.10, pdf export started working again. @VesnaT, look, pyqtgraph did it again.

**Comment by markotoplak** [comment]
I bisected this and found out that this started failing after pyqtgraph/pyqtgraph#321 was merged.

**Comment by markotoplak** [comment]
I suggesting an upstream fix in pyqtgraph/pyqtgraph#1458. Let's see what are the going to say...

I could also probably do the same thing as in that PR just before PDF export so that this will work with current pyqtgraph.
