### ISSUE TITLE
Changing values of disabled spins

### ISSUE THREAD

**Issue by janezd** [biolab/orange-widget-base#134]
`orangewidgets.gui.SpinBoxMixin` does not check whether the spin is enabled and thus allows the user to change values of disabled spins by clicking and dragging.

**Comment by janezd** [comment]
@lanzagar also reported that text in spins can no longer be selected. Please check.

**Comment by markotoplak** [comment]
I had the same report about the non-selectability of text by @borondics. I could easily select it with my trackpoint, but he was having problems with the trackpad. He could double-click and select all of it, but he could not select parts of the input number.

**Comment by borondics** [comment]
Double click still works on Mac but the hold-and-paint-over type selection is very hard. If the mouse button is pressed inside the text box, the movement of text selection has to be very horizontal otherwise the value of the box changes instead of text selection.

**Comment by janezd** [comment]
I think this happens because the dragging event is intercepted by methods that change the spinbox's value on dragging. To solve this, we should distinguish between vertical and horizontal dragging. :)

A simpler solution would be to change the value only if dragging is initiated when the mouse is on the right-hand part, the arrow icons, not on lineedit part.
