### ISSUE TITLE
Opening a workflow results in many crashes

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange-widget-base#193]
##### Orange version

3.32.0 / 3.31.0

##### Expected behavior
Old workflows can be opened on newer version.

##### Actual behavior
```
Stack Trace:
Traceback (most recent call last):
  File "/Users/ajda/orange/orange-widget-base/orangewidget/widget.py", line 1063, in showEvent
    self.__restoreWidgetGeometry(bytes(self.savedWidgetGeometry))
  File "/Users/ajda/orange/orange-widget-base/orangewidget/widget.py", line 956, in __restoreWidgetGeometry
    self.move(x, y)
TypeError: arguments did not match any overloaded call:
  move(self, QPoint): argument 1 has unexpected type 'float'
  move(self, int, int): argument 1 has unexpected type 'float'

```

##### Steps to reproduce the behavior
Open the below workflow (no data required) and click on any widget.

##### Additional info (worksheets, data, screenshots, ...)
[Uploading untitled_naloga 2.ows.zip…]()

**Comment by ajdapretnar** [comment]
Ok, I forgot to specify the workflow was constructed on Windows machine with Orange version 3.31.0.
I try to open it on OSX with 3.32.0.

**Comment by ajdapretnar** [comment]
Nevermind (practically), this happens only on Python 3.10.

**Comment by markotoplak** [comment]
But is very import that we get it fixed... Thanks, @ajdapretnar.
