### ISSUE TITLE
ARIMA Model Widget AttributeError: 'NoneType' object has no attribute 'control'

### ISSUE THREAD

**Issue by layudhi** [biolab/orange-widget-base#205]
##### Orange version

Orange 3.32

##### Expected behavior
ARIMA Model shows output without error

##### Actual behavior
ARIMA Model Widget AttributeError: 'NoneType' object has no attribute 'control'

##### Steps to reproduce the behavior
When drag ARIMA Model to workflow canvas, or Click it on Widget window

##### Additional info (worksheets, data, screenshots, ...)

Error Code :
![image](https://user-images.githubusercontent.com/102269946/174238483-206755c3-6b88-4263-872c-2b4f488183cc.png)

![image](https://user-images.githubusercontent.com/102269946/174238504-d5b6a9c9-5297-4c8d-9685-9b107bd1d56a.png)

**Comment by janezd** [comment]
Replicate of #209.
