### ISSUE TITLE
ListViewSearch: Does not filter on changed data

### ISSUE THREAD

**Issue by mw25** [biolab/orange-widget-base#212]
##### Orange version
orange-widget-base:            4.18.0.dev0+86a1dd8 
Orange3:                       3.32.0.dev0+2b857a3 

##### Expected behavior
I enter a text in "Filter..." and the variables are filtered.

##### Actual behavior
Filtering does not work properly if the input data has changed.
After the filter text is deleted and re-entered it works.
When the data changes again, it does not work again.

##### Steps to reproduce the behavior

- Load Iris Dataset 
- Connect Data to Widget with ListViewSearch (I tested with Unique and Group by)
- Type "sepal" --> Only iris is filtered
- remove filter text and type again "sepal" --> iris, petal length and petal width are filtered
- remove connection between the widgets and connect again
- Type "sepal" --> Only iris is filtered

The same behavior if the data is changed e.g. with Edit Domain.

**Comment by ajdapretnar** [comment]
I can confirm.
