### ISSUE TITLE
Indicate uncommitted changes at the widget and canvas levels

### ISSUE THREAD

**Issue by pisarik** [biolab/orange-widget-base#226]
Hi! As always, during summer school we are getting some new ideas to improve Orange:)

**What's your use case?**
During summer school lectures, students followed some instructions in Orange and often we had to remind them to not forget to press `Commit` button after they made changes to widget's settings (most often in Preprocessing widget).

**What's your proposed solution?**
That would be nice to indicate that the settings of a widget were changed and the `Commit` button likely have to be pressed (when auto-commit is disabled). The way to indicate it might be to change a color of `Commit` button from gray to red or something like this. Additionally that would be cool to add a red badge on a widget icon at canvas when the changes of its settings were not applied.

**Comment by janezd** [comment]
Closed via #228.
