### ISSUE TITLE
TimeoutError() in webview: better error message

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange-widget-base#31]
##### Orange version

3.24.dev

##### Expected behavior
User gets an informative message.

##### Actual behavior
An error appears and probably most users won't understand why this happens and how to fix it.

##### Steps to reproduce the behavior
Load a large data set and open a widget with a webview, say Line Chart.

##### Additional info (worksheets, data, screenshots, ...)
The error keeps popping up and when I close it, I can still see the plot.

**Comment by janezd** [comment]
This would probably have to be done per-widget. With removal of highcharts from timeseries add-on, no "official" add-ons will use webview, hence I think this would also close this issue.

**Comment by ajdapretnar** [comment]
Text add-on (namely Corpus Viewer) still uses Webview.

That said, I haven't seen this issue in a while now.
