### ISSUE TITLE
Q: widget: may be missing: 'classification tree' 

### ISSUE THREAD

**Issue by RogerWeihrauch** [biolab/orange-widget-base#32]
##### Expected behavior
I want to select the 'classification tree' widget when right clicking on the canvas.

##### Actual behavior
When 'creating'/selecting a new widget in the canvas: right click and 'searching' for "classification tree" ther is no such widget to select.

##### Steps to reproduce the behavior
Just do a right click on the canvas, enter first few characters like as 'class' and see that here is no selection possible which sounds like classification tree.

##### Additional info (worksheets, data, screenshots, ...)
I tried to follow the youtube tutorial "Getting started with Orange" and I am stuch in chapter06: time: 1:00 from 3:45.
<img width="553" alt="Screen Shot 2019-12-19 at 4 49 45 PM" src="https://user-images.githubusercontent.com/15932486/71187613-b02ab000-227f-11ea-9064-cbbb2ea85345.png">

**Comment by RogerWeihrauch** [comment]
Also I get this error while starting Orange3 from out of Anaconda:
libpng warning: iCCP: known incorrect sRGB profile
Execution of PAC script at "http://wpad/wpad.dat" failed: The operation couldn’t be completed. (NSURLErrorDomain error -1003.)
Execution of PAC script at "http://wpad/wpad.dat" failed: The operation couldn’t be completed. (NSURLErrorDomain error -1003.)
Execution of PAC script at "http://wpad/wpad.dat" failed: The operation couldn’t be completed. (NSURLErrorDomain error -1003.)
Execution of PAC script at "http://wpad/wpad.dat" failed: The operation couldn’t be completed. (NSURLErrorDomain error -1003.)
Execution of PAC script at "http://wpad/wpad.dat" failed: The operation couldn’t be completed. (NSURLErrorDomain error -1003.)
Execution of PAC script at "http://wpad/wpad.dat" failed: The operation couldn’t be completed. (NSURLErrorDomain error -1003.)
Execution of PAC script at "http://wpad/wpad.dat" failed: The operation couldn’t be completed. (NSURLErrorDomain error -1003.)
Execution of PAC script at "http://wpad/wpad.dat" failed: The operation couldn’t be completed. (NSURLErrorDomain error -1003.)
Execution of PAC script at "http://wpad/wpad.dat" failed: The operation couldn’t be completed. (NSURLErrorDomain error -1003.)
Execution of PAC script at "http://wpad/wpad.dat" failed: The operation couldn’t be completed. (NSURLErrorDomain error -1003.)
Execution of PAC script at "http://wpad/wpad.dat" failed: The operation couldn’t be completed. (NSURLErrorDomain error -1003.)
Execution of PAC script at "http://wpad/wpad.dat" failed: The operation couldn’t be completed. (NSURLErrorDomain error -1003.)
Execution of PAC script at "http://wpad/wpad.dat" failed: The operation couldn’t be completed. (NSURLErrorDomain error -1003.)
Execution of PAC script at "http://wpad/wpad.dat" failed: The operation couldn’t be completed. (NSURLErrorDomain error -1003.)

**Comment by janezd** [comment]
Fixed via https://github.com/biolab/orange3/pull/4283.
