### ISSUE TITLE
WidgetTest: Falling test when invoking get_output() with 1. parameter as string

### ISSUE THREAD

**Issue by VesnaT** [biolab/orange-widget-base#50]
##### Orange version
Master

##### Expected behavior
Passing widget tests.

##### Actual behavior
Falling widget tests.

##### Steps to reproduce the behavior
Run any widget test where `get_output()` is invoked with `output` parameter as `string` instead of `Output` signal (e.g. `TestOWDataSampler`).

**Comment by VesnaT** [comment]
Bigger problem than the issue itself is, that we didn't discover it before merging the problematic change.
However, I think we should be testing orange repository with master branch of orange-widget-base as well.

**Comment by JakaKokosar** [comment]
I will add this later this week.
