### ISSUE TITLE
Error message not clickable

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange-widget-base#63]
##### Orange version

3.26.0.dev

##### Expected behavior
The user can see the entire error message. If the message is too long, one can click on the message and see it.

##### Actual behavior
The error message is not shown entirely for some widgets.

##### Steps to reproduce the behavior
File - Select Columns (remove all features from attributes) - Logistic Regression (or Naive Bayes).

**Comment by ajdapretnar** [comment]
<img width="208" alt="Screen Shot 2020-05-05 at 11 47 02" src="https://user-images.githubusercontent.com/12524972/81053928-26921c80-8ec6-11ea-9301-abcf9cd7c6f4.png">

**Comment by lanzagar** [comment]
The whole message is shown in a tooltip, but I agree showing it on click would also be nice.
(currently, if you click on it, then tooltip is not shown)
