### ISSUE TITLE
Feature Request: Use Exact Number of Attributes Instead of Up To Number of Attributes

### ISSUE THREAD

**Issue by jkaupanger** [biolab/orange-widget-base#87]
##### Orange version

3.26.0

##### Feature Request
In the Mosaic Display widget (and probably in others, as well), you can ask for informative comparisons, and the program will go through and rank all of the comparisons. You also have the option to limit how many attributes to look at. I haven't used it much, but it seems as though going all the way up to 4 (the max) will take a long time to find all of the useful comparisons.

What if there was an option where, instead of "up to" a certain number, you could include "exactly" a certain number. For instance, I could have it only give me comparisons of exactly three attributes. That way, I could start at one and look at all of those. Then I could jump to two, then look at those, etc.

**Comment by janezd** [comment]
The issue would be noted sooner if posted to https://github.com/biolab/orange3, which contains Orange widgets. This repo is more general.

Implementation of what you suggest is at https://github.com/biolab/orange3/pull/4990.

The only other such widget, to my knowledge, is Radviz.
